name: my_favorite_books
description: My Favorite Books
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  easy_localization: ^3.0.4
  either_dart: ^1.0.0
  equatable: ^2.0.5
  fancy_dio_inspector: ^1.6.1
  flash: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  gap: ^3.0.1
  get_it: ^7.6.7
  hive_flutter: ^1.1.0
  injectable: ^2.3.2
  intl: ^0.18.0
  retrofit: ^4.1.0
  theme_tailor_annotation: ^2.1.0

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.1.0
  very_good_analysis: ^5.1.0
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2
  hive_generator: ^2.0.1
  theme_tailor: ^2.1.0
  build_runner: ^2.4.8
  mockito: ^5.4.4
  mock_web_server: ^5.0.0-nullsafety.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/translations/
